---
title: "Analisis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Paquetes

```{r}
library(readxl)
library(ggplot2)
library(dplyr)
```

# Data

```{r}
datos_falt <- read_excel("../Data/Estimación_de_datos_faltantes.xlsx",
                         sheet = "chusis")
datos_falt
```

# EDA

```{r}
datos_falt %>% 
  group_by(month) %>% 
  summarise(mean_temp = mean(temp_max),
            mean_rain = mean(rain))
```

De 1972 a 2015 (43)

```{r}
colors <- c("Temp" = "#D8B619", "Prec" = "black")

datos_falt %>% 
  group_by(month) %>% 
  summarise(mean_temp = mean(temp_max),
            mean_rain = mean(rain)) %>% 
  ggplot(aes(label = round(mean_temp, 1))) +
  geom_bar(aes(x = month, y = mean_rain, color = "Temp"), stat = "identity", 
           fill = "#D8B619", alpha = .85) +
  geom_line(aes(x = month, y = mean_temp/2, color = "Prec")) +
  geom_point(aes(x = month, y = mean_temp/2), size = 1.5)+
  scale_x_continuous(breaks = 1:12) +
  scale_y_continuous(
    breaks = seq(0, 30, 4),
    name = "Temp",
    sec.axis = sec_axis(~.*(0.5), name = "Precipitacion", 
                        breaks = seq(0,15, 2))
  ) +
  # geom_text(aes(x = month, y = mean_temp), nudge_y = 1) +
  labs(x = "Meses", title = "Temp y Prec de Chusis", 
       caption = "Fuente: Yo\n*Datos desde 1972 a 2015",
       color  = "Tipo") +
  scale_color_manual(values = colors)
```

```{r}
# Exportando ggplots
ggsave(filename = "../Graficos/ejemplo.png",
       plot = gplot_chusis)
```
